change to F# rewrite system

diff --git a/env b/env
--- a/env
+++ b/env
@@ -1,7 +1,26 @@
-#!/bin/bash
+#!/usr/bin/zsh
 # environment variables (source it from your .bashrc?)
 
-export skalchdir="$(dirname "$(readlink -f "$0")")"
+function getpath() {
+    [ -e "$*" ] || { echo "path '$*' doesn't exist!" >&2; exit 1; }
+    readlink -f "$*"
+}
+
+export skalchdir="$(dirname "$(getpath "$0")")"
 export grgenfiles="$skalchdir"/plugin/src/main/grgen
+export sugaredtest="$skalchdir"/base/src/test/scala/angelic/simple/SugaredTest.scala.ast.gxl
+export libgrg="$(getpath "$skalchdir"/../grgen/engine-net-2/bin)"
+export stagetf="$(getpath "$skalchdir"/../grgen/engine-net-2/FSharpBindings)"
+stagetf_sources_array=($(for i in $(cat "$stagetf"/filelist); do echo "$stagetf"/"$i"; done))
+export stagetf_sources="${stagetf_sources_array}"
+export MONO_PATH="$libgrg"
 
 function g() { grep -E "$@" **/*(grg|grs) | sed '/\/gen\//d'; }
+function tf() {
+    mono "$grgenfiles"/transformer.exe --goal sketch "$@"
+}
+function tf-test() { tf $sugaredtest "$@"; }
+
+if ! [ -d "$libgrg" ]; then
+    echo "ERROR -- '$libgrg' doesn't exist! Please check out GrGen!" >&2; exit 1
+fi
